services:
  - type: web
    name: secretnotfound
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: GOOGLE_AI_API_KEY
    #   sync: false
    # - key: FIREBASE_PROJECT_ID
    #   sync: false
    # - key: FIREBASE_API_KEY
    #   sync: false
